package ops

// RegisterAll registers all implemented operators into the registry.
// If config is nil, DefaultKernelConfig is used.
func RegisterAll(r *Registry, config ...*KernelConfig) {
	var kc *KernelConfig
	if len(config) > 0 && config[0] != nil {
		kc = config[0]
	} else {
		kc = DefaultKernelConfig()
	}
	// Math ops
	r.Register("Add", opAdd)
	r.Register("Sub", opSub)
	r.Register("Mul", opMul)
	r.Register("Div", opDiv)
	r.Register("Mod", opMod)

	// MatMul ops (config-aware: tiled GEMM)
	r.Register("MatMul", makeMatMul(kc))
	r.Register("Gemm", opGemm)

	// Activation ops
	r.Register("Relu", opRelu)
	r.Register("LeakyRelu", opLeakyRelu)
	r.Register("PRelu", opPRelu)
	r.Register("Elu", opElu)
	r.Register("Sigmoid", opSigmoid)
	r.Register("HardSigmoid", opHardSigmoid)
	r.Register("HardSwish", opHardSwish)
	r.Register("Tanh", opTanh)
	r.Register("Softmax", opSoftmax)

	// Shape ops
	r.Register("Reshape", opReshape)
	r.Register("Transpose", opTranspose)
	r.Register("Squeeze", opSqueeze)
	r.Register("Unsqueeze", opUnsqueeze)
	r.Register("Flatten", opFlatten)
	r.Register("Concat", opConcat)

	// Conv/Pool ops (config-aware: depthwise, 1x1, parallel, pool fast path)
	r.Register("Conv", makeConv(kc))
	r.Register("ConvTranspose", makeConvTranspose(kc))
	r.Register("FusedConv", makeFusedConv(kc))
	r.Register("MaxPool", makeMaxPool(kc))
	r.Register("AveragePool", opAveragePool)
	r.Register("GlobalAveragePool", opGlobalAveragePool)

	// Norm ops
	r.Register("BatchNormalization", opBatchNormalization)
	r.Register("LRN", opLRN)
	r.Register("InstanceNormalization", opInstanceNormalization)

	// Data ops
	r.Register("Constant", opConstant)
	r.Register("Identity", opIdentity)
	r.Register("Gather", opGather)

	// Extra ops (Model Zoo models)
	r.Register("Dropout", opDropout)
	r.Register("Clip", opClip)
	r.Register("Shape", opShape)
	r.Register("ReduceMean", opReduceMean)
	r.Register("CumSum", opCumSum)
	r.Register("Split", opSplit)

	// Unary/Cast ops
	r.Register("Log", opLog)
	r.Register("Abs", opAbs)
	r.Register("Sin", opSin)
	r.Register("Cos", opCos)
	r.Register("Sqrt", opSqrt)
	r.Register("Neg", opNeg)
	r.Register("Erf", opErf)
	r.Register("Pow", opPow)
	r.Register("Cast", opCast)
	r.Register("Equal", opEqual)
	r.Register("Greater", opGreater)
	r.Register("GreaterOrEqual", opGreaterOrEqual)
	r.Register("Less", opLess)
	r.Register("Where", opWhere)
	r.Register("Or", opOr)
	r.Register("NonZero", opNonZero)
	r.Register("OneHot", opOneHot)
	r.Register("Expand", opExpand)
	r.Register("Floor", opFloor)
	r.Register("Exp", opExp)
	r.Register("And", opAnd)
	r.Register("Min", opMin)
	r.Register("Max", opMax)
	r.Register("Reciprocal", opReciprocal)
	r.Register("Range", opRange)

	// Tensor manipulation ops
	r.Register("Slice", opSlice)
	r.Register("Pad", opPad)
	r.Register("Tile", opTile)
	r.Register("TopK", opTopK)
	r.Register("ReduceMax", opReduceMax)
	r.Register("ReduceProd", opReduceProd)
	r.Register("ReduceSum", opReduceSum)
	r.Register("ReduceSumSquare", opReduceSumSquare)
	r.Register("GatherElements", opGatherElements)
	r.Register("GatherND", opGatherND)
	r.Register("ScatterND", opScatterND)
	r.Register("NonMaxSuppression", opNonMaxSuppression)
	r.Register("ArgMax", opArgMax)
	r.Register("Resize", opResize)
	r.Register("Upsample", opUpsample)
	r.Register("GridSample", opGridSample)
	r.Register("LayerNormalization", opLayerNormalization)

	// RNN ops
	r.Register("LSTM", opLSTM)
	r.Register("GRU", opGRU)

	// Control flow ops
	r.Register("If", opIf)
	r.Register("Not", opNot)
	r.Register("Size", opSize)
	r.Register("ConstantOfShape", opConstantOfShape)

	// Math extra
	r.Register("Ceil", opCeil)
	r.Register("Round", opRound)
	r.Register("Sign", opSign)
	r.Register("Tan", opTan)
	r.Register("Sinh", opSinh)
	r.Register("Cosh", opCosh)
	r.Register("Asin", opAsin)
	r.Register("Acos", opAcos)
	r.Register("Atan", opAtan)
	r.Register("LessOrEqual", opLessOrEqual)
	r.Register("Gelu", opGelu)
	r.Register("Mish", opMish)
	r.Register("Selu", opSelu)
	r.Register("Softplus", opSoftplus)
	r.Register("Softsign", opSoftsign)
	r.Register("Swish", opSwish)
	r.Register("LogSoftmax", opLogSoftmax)
	r.Register("GlobalMaxPool", opGlobalMaxPool)
	r.Register("DepthToSpace", opDepthToSpace)
	r.Register("SpaceToDepth", opSpaceToDepth)
	r.Register("ReduceMin", opReduceMin)
	r.Register("ReduceL1", opReduceL1)
	r.Register("ReduceL2", opReduceL2)
	r.Register("Sum", opSum)
	r.Register("Mean", opMean)
	r.Register("ScatterElements", opScatterElements)
	r.Register("Trilu", opTrilu)
	r.Register("GroupNormalization", opGroupNormalization)
	r.Register("RMSNormalization", opRMSNormalization)
	r.Register("SimplifiedLayerNormalization", opRMSNormalization) // ORT alias

	// Extra math/comparison/logic
	r.Register("IsNaN", opIsNaN)
	r.Register("IsInf", opIsInf)
	r.Register("CastLike", opCastLike)
	r.Register("ArgMin", opArgMin)
	r.Register("Acosh", opAcosh)
	r.Register("Asinh", opAsinh)
	r.Register("Atanh", opAtanh)
	r.Register("Celu", opCelu)
	r.Register("Hardmax", opHardmax)
	r.Register("Shrink", opShrink)
	r.Register("ThresholdedRelu", opThresholdedRelu)
	r.Register("Xor", opXor)
	r.Register("ReduceLogSum", opReduceLogSum)
	r.Register("ReduceLogSumExp", opReduceLogSumExp)
	r.Register("EyeLike", opEyeLike)
	r.Register("Compress", opCompress)
	r.Register("Unique", opUnique)
	r.Register("MaxRoiPool", opMaxRoiPool)
	r.Register("DynamicQuantizeLinear", opDynamicQuantizeLinear)
	r.Register("LpNormalization", opLpNormalization)
	r.Register("MeanVarianceNormalization", opMeanVarianceNormalization)
	r.Register("BitShift", opBitShift)
	r.Register("BitwiseAnd", opBitwiseAnd)
	r.Register("BitwiseNot", opBitwiseNot)
	r.Register("BitwiseOr", opBitwiseOr)
	r.Register("BitwiseXor", opBitwiseXor)
	r.Register("Det", opDet)
	r.Register("Scan", opScan)

	// Specialist ops
	r.Register("Einsum", opEinsum)
	r.Register("RNN", opRNN)
	r.Register("Loop", opLoop)
	r.Register("DequantizeLinear", opDequantizeLinear)
	r.Register("QuantizeLinear", opQuantizeLinear)
	r.Register("QLinearConv", opQLinearConv)
	r.Register("QLinearMatMul", opQLinearMatMul)
	r.Register("DFT", opDFT)
	r.Register("STFT", opSTFT)
	r.Register("MelWeightMatrix", opMelWeightMatrix)
	r.Register("RoiAlign", opRoiAlign)
	r.Register("DeformConv", opDeformConv)
	r.Register("Attention", opAttention)
	r.Register("RotaryEmbedding", opRotaryEmbedding)

	// Fused ops (config-aware: fastErf)
	r.Register("FastGELU", makeFastGELU(kc))
	r.Register("FusedMatMul", opFusedMatMul)
	r.Register("FusedAffine", opFusedAffine)
}
